# Azure OpenAI Configuration
AZURE_OPENAI_ENDPOINT = "https://stock-prediction.openai.azure.com/"
AZURE_OPENAI_KEY = "1XqsN8HXTjdR2D3XhUspQiPnTZEow96GaAEBq9T9aUWo975wg0AeJQQJ99BFACYeBjFXJ3w3AAABACOGmQog"
AZURE_OPENAI_DEPLOYMENT = "gpt-4.1"
